apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-network-policy
  labels:
    app: redis
spec:
  podSelector:
    matchLabels:
      app: redis
  policyTypes:
    - Ingress
  ingress:
    # Allow traffic from pods in the SAME namespace
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 6379
    # Allow traffic from Traefik (for future external access if needed)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
      ports:
        - protocol: TCP
          port: 6379
