apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`placeholder.example.com`)
      services:
        - name: n8n
          port: 5678
  tls:
    secretName: placeholder-tls
