apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml

images:
  - name: n8nio/n8n
    newName: n8nio/n8n
    newTag: latest
