apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.secretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.database.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
  POSTGRES_DB: {{ .Values.database.name | quote }}
