# InfisicalSecret for GHCR Docker Pull Credentials
# Syncs GHCR_USERNAME and GHCR_TOKEN from Infisical to create kubernetes.io/dockerconfigjson
{{- if .Values.ghcr.enabled }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ .Values.name }}-ghcr-infisical
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Values.name }}
    app.kubernetes.io/managed-by: dockify
    dockify.cloud/deployment-id: {{ .Values.deploymentId | quote }}
spec:
  hostAPI: {{ .Values.ghcr.hostAPI }}
  resyncInterval: {{ .Values.ghcr.resyncInterval }}
  authentication:
    universalAuth:
      credentialsRef:
        secretName: {{ .Values.ghcr.credentialsRef.secretName }}
        secretNamespace: {{ .Values.ghcr.credentialsRef.secretNamespace }}
      secretsScope:
        projectId: {{ .Values.ghcr.projectId | quote }}
        envSlug: {{ .Values.ghcr.envSlug }}
        secretsPath: {{ .Values.ghcr.secretsPath }}
        recursive: false
  managedSecretReference:
    secretName: ghcr-credentials
    secretNamespace: {{ .Values.namespace }}
    secretType: kubernetes.io/dockerconfigjson
    creationPolicy: Owner
    template:
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"username":"{{ "{{" }} .GHCR_USERNAME.Value {{ "}}" }}","password":"{{ "{{" }} .GHCR_TOKEN.Value {{ "}}" }}","auth":"{{ "{{" }} printf "%s:%s" .GHCR_USERNAME.Value .GHCR_TOKEN.Value | b64enc {{ "}}" }}"}}}
{{- end }}
