{{- if .Values.infisical.enabled }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ .Values.name }}-infisical
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Values.name }}
    app.kubernetes.io/managed-by: dockify
    dockify.cloud/deployment-id: {{ .Values.deploymentId | quote }}
spec:
  hostAPI: {{ .Values.infisical.hostAPI }}
  resyncInterval: {{ .Values.infisical.resyncInterval }}
  authentication:
    universalAuth:
      credentialsRef:
        secretName: {{ .Values.infisical.credentialsRef.secretName }}
        secretNamespace: {{ .Values.infisical.credentialsRef.secretNamespace }}
      secretsScope:
        projectId: {{ .Values.infisical.projectId | quote }}
        envSlug: {{ .Values.infisical.envSlug }}
        secretsPath: {{ .Values.infisical.secretsPath }}
        recursive: false
  managedSecretReference:
    secretName: {{ .Values.name }}-secrets
    secretNamespace: {{ .Values.namespace }}
    secretType: Opaque
    creationPolicy: Owner
    template:
      includeAllSecrets: true
{{- end }}
