apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init-scripts
data:
  # This file will be populated by Kustomize patches when pgvector is enabled
  # The init script will be mounted to /docker-entrypoint-initdb.d/
  .keep: ""
