apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgresql-network-policy
  labels:
    app: postgresql
spec:
  podSelector:
    matchLabels:
      app: postgresql
  policyTypes:
    - Ingress
  ingress:
    # Allow traffic from pods in the SAME namespace
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 5432
    # Allow traffic from Traefik (for external access via IngressRouteTCP)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
      ports:
        - protocol: TCP
          port: 5432
