apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  labels:
    app: pgbouncer
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/component: connection-pooler
    app.kubernetes.io/part-of: postgresql-cluster
spec:
  replicas: 2  # Multiple replicas for HA
  selector:
    matchLabels:
      app: pgbouncer
      app.kubernetes.io/name: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
        app.kubernetes.io/name: pgbouncer
        app.kubernetes.io/component: connection-pooler
        app.kubernetes.io/part-of: postgresql-cluster
    spec:
      containers:
        - name: pgbouncer
          image: edoburu/pgbouncer:latest
          ports:
            - containerPort: 6432
              name: pgbouncer
          env:
            # Database connection (edoburu/pgbouncer format)
            - name: DATABASES_HOST
              value: "postgresql"
            - name: DATABASES_PORT
              value: "5432"
            - name: DATABASES_DBNAME
              value: "mydb"
            - name: DATABASES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: username
            - name: DATABASES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: password
            # PgBouncer settings
            - name: POOL_MODE
              value: "transaction"
            - name: MAX_CLIENT_CONN
              value: "1000"
            - name: DEFAULT_POOL_SIZE
              value: "25"
            - name: MIN_POOL_SIZE
              value: "5"
            - name: RESERVE_POOL_SIZE
              value: "5"
            - name: RESERVE_POOL_TIMEOUT
              value: "5"
            - name: MAX_DB_CONNECTIONS
              value: "100"
            - name: MAX_USER_CONNECTIONS
              value: "100"
            # Timeouts
            - name: SERVER_IDLE_TIMEOUT
              value: "600"
            - name: SERVER_LIFETIME
              value: "3600"
            - name: QUERY_WAIT_TIMEOUT
              value: "120"
            - name: CLIENT_IDLE_TIMEOUT
              value: "0"
            - name: CLIENT_LOGIN_TIMEOUT
              value: "60"
            # Auth
            - name: AUTH_TYPE
              value: "md5"  # edoburu supports md5/plain/trust
            - name: AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: username
            - name: AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: password
            # Logging
            - name: LOG_CONNECTIONS
              value: "1"
            - name: LOG_DISCONNECTIONS
              value: "1"
            - name: LOG_POOLER_ERRORS
              value: "1"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          # Health checks
          livenessProbe:
            tcpSocket:
              port: 6432
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 6432
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      # Anti-affinity to spread replicas across nodes
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - pgbouncer
                topologyKey: kubernetes.io/hostname
      # Security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001