apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    # CRITICAL: Use specific instance label for proper isolation
    # The instance label will be unique for each deployment
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql  # Will be unique per deployment