# Default values for NGINX deployment
# These will be overridden by Dockify API via Kustomize patches

app:
  name: nginx

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

replicas: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  hostname: example.com
  tls:
    secretName: default-cert

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "200m"
