apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      # Image pull secret for private registries (GHCR, Docker Hub, etc.)
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: app
        image: app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
