{{- if .Values.infisical.enabled }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ .Values.name }}-infisical
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: {{ .Values.name }}
    app.kubernetes.io/managed-by: dockify
spec:
  hostAPI: {{ .Values.infisical.hostAPI }}
  resyncInterval: {{ .Values.infisical.resyncInterval }}
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: {{ .Values.infisical.projectId }}
        envSlug: {{ .Values.infisical.environment }}
        secretsPath: {{ .Values.infisical.secretPath }}
      credentialsRef:
        secretName: {{ .Values.infisical.credentialsSecretName }}
        secretNamespace: {{ .Values.infisical.credentialsNamespace }}
  managedSecretReference:
    secretName: {{ .Values.name }}-secret
    secretNamespace: {{ .Values.namespace }}
    creationPolicy: Owner
{{- end }}
