# InfisicalSecret - syncs secrets from Infisical to K8s Secret
# Infisical is the source of truth - changes in Infisical UI auto-sync here
{{- if .Values.infisical.enabled }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ .Values.name }}-infisical
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: {{ .Values.name }}
    app.kubernetes.io/managed-by: dockify
spec:
  hostAPI: {{ .Values.infisical.hostAPI | default "https://vault.dockify.app/api" }}
  resyncInterval: {{ .Values.infisical.resyncInterval | default 15 }}
  authentication:
    universalAuth:
      credentialsRef:
        secretName: {{ .Values.infisical.credentialsSecretName | default "infisical-machine-identity" }}
        secretNamespace: {{ .Values.infisical.credentialsNamespace | default "infisical-system" }}
      secretsScope:
        projectId: {{ .Values.infisical.projectId | quote }}
        envSlug: {{ .Values.infisical.environment | default "dev" | quote }}
        secretsPath: {{ .Values.infisical.secretPath | quote }}
        recursive: false
  managedSecretReference:
    secretName: {{ .Values.name }}-secret
    secretNamespace: {{ .Values.namespace }}
    secretType: Opaque
    creationPolicy: Owner
    template:
      includeAllSecrets: true
{{- end }}
