apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/name: n8n
    app.kubernetes.io/instance: {{ .Values.name }}
    app.kubernetes.io/managed-by: dockify
type: Opaque
stringData:
  # Encryption key for credentials (REQUIRED for persistence)
  # n8n uses this to encrypt stored credentials
  N8N_ENCRYPTION_KEY: {{ .Values.encryptionKey | quote }}
