apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 3
  imageName: postgres:16

  # Storage configuration
  storage:
    size: 1Gi
    storageClass: local-path

  # Bootstrap configuration
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: postgres-app-user

  # Monitoring
  monitoring:
    enablePodMonitor: true

  # PostgreSQL configuration
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
