apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "PLACEHOLDER",
          "password": "PLACEHOLDER",
          "email": "noreply@example.com",
          "auth": "PLACEHOLDER"
        }
      }
    }
